apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-web
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: grafana.multi.io
    http:
      paths:
      - backend:
          serviceName: prometheus-operator-grafana
          servicePort: 80
        path: /

