apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: guest-sa-1
  name: role-1
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-bind-1
  namespace: default
subjects:
- kind: ServiceAccount
  name: role-1
  namespace: default
roleRef:
  kind: Role
  name: role-1
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-1
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
