apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeapps-ui
  namespace: kubeapps
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: kubeapps.multi.io
    http:
      paths:
      - backend:
          serviceName: kubeapps-internal-dashboard
          servicePort: 8080

